### ISSUE TITLE
Problems with sudo mode

### ISSUE THREAD

**Issue by jankap** [buschmais/redmics#17]
Hey, thank you for your work. Unfortunately redmine 3.1 does not work. When I try to open the URL following happens:

``` 
ArgumentError (wrong number of arguments (2 for 0)):
  lib/redmine/sudo_mode.rb:64:in `sudo_mode'


Processing by UsErrorsController#error_500 as ICS
  Parameters: {"key"=>"50a49df4e7998022972efe30e3321a5d6741d5bf", "project_id"=>"test-project", "assignment"=>"my"}
  Current user: jan (id=3)
  Rendered text template (0.0ms)
Completed 500 Internal Server Error in 4ms (Views: 0.5ms | ActiveRecord: 0.7ms)
Started GET "/redmine/icalendar/test-project/my/issues.ics?key=50a49df4e7998022972efe30e3321a5d6741d5bf" for 192.168.56.1 at 2015-12-18 13:03:56 +0100
Processing by ICalendarController#index as ICS
  Parameters: {"key"=>"50a49df4e7998022972efe30e3321a5d6741d5bf", "project_id"=>"test-project", "assignment"=>"my"}
  Current user: jan (id=3)
Completed 500 Internal Server Error in 35ms (ActiveRecord: 6.7ms)

ArgumentError (wrong number of arguments (2 for 0)):
  lib/redmine/sudo_mode.rb:64:in `sudo_mode'


Processing by UsErrorsController#error_500 as ICS
  Parameters: {"key"=>"50a49df4e7998022972efe30e3321a5d6741d5bf", "project_id"=>"test-project", "assignment"=>"my"}
  Current user: jan (id=3)
  Rendered text template (0.0ms)
Completed 500 Internal Server Error in 5ms (Views: 0.9ms | ActiveRecord: 0.8ms)
```

Do you have any ideas fixing that, or do you need further information?

Thank you!

**Comment by fs5** [comment]
I have just tried HEAD of master and 3.1-stable branch of redmine. I cannot observe any issues with sudo-mode enabled. Please reopen this bug-report with a stacktrace where I can see how your error relates to the redmics plug-in.

**Comment by jankap** [comment]
Hi, sorry for the late response, anyways, happy new year :)

I just updated to redmine 3.2-stable, the error is still the same. How can I generate an appropiate stack trace you need? The logger_level is set to :debug, but there aren't any new information.

Thanks

**Comment by fs5** [comment]
The SQL statements look pretty much OK, the api-key was identified to belong to user 3 and the "testproject" has id 7. Then there are the expected queries "FROM `issues`" "and FROM `versions`"

What puzzles me is "UsErrorsController" and "plugin_usability". It looks like you also have enabled some "Usability" plugin. Could you please specify where I can get this from to further test for possible incompatibilities?

**Comment by jankap** [comment]
Hi,

the Usability plugin is from here https://www.redmine.org/plugins/usability or http://rmplus.pro/en/redmine/plugins/usability. I think UsErrorsController belongs to this plugin. It's useful to hide the sidebar and modify the estimated times a bit.

**Comment by fs5** [comment]
It is not the usability plugin - I cannot see an issue with that plugin enabled. Probably some other plugin that does something weird after calling ICalendarController#index. I suggest you disable all other plugins and then re-enable them one by one until the error occurs.
