### ISSUE TITLE
plugin doesnt work with redmine 3.2.0

### ISSUE THREAD

**Issue by HighwayStar** [buschmais/redmics#18]
I've installed plugin on clean redmine 3.2.0 installation and it seems not work.

When I go to Issues list in any project I get 404 page. Same for plugin settings page.

production.log when getting 404:

```
Started GET "/settings/plugin/redmine_ics_export" for 127.0.0.1 at 2016-01-19 15:29:22 +0800
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_ics_export"}
  Current user: admin (id=1)
  Rendered settings/plugin.html.erb within layouts/admin (7.5ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.3ms)
Completed 404 Not Found in 146ms (Views: 10.5ms | ActiveRecord: 115.5ms)

```

**Comment by fs5** [comment]
Sorry, I cannot reproduce this. "/settings/plugin/redmine_ics_export" works as expected in Redmine branch "3.2-stable".

Please verify that redmine/plugins/redmine_ics_export/app/views/settings/_redmics_settings.html.erb exists. Perhaps your download is incomplete or you put in the plugin into an unsupported directory.

Please reopen the ticket with a more detailed reproducer.

**Comment by HighwayStar** [comment]
Thank you for reply, I forget to clone plugin to redmine_ics_export, but cloned to redmics, this caused issue. I moved redmics to redmine_ics_export and now it works fine.
