### ISSUE TITLE
How are issues spanning over multiple days displayed? :question:

### ISSUE THREAD

**Issue by Paul-Ver** [buschmais/redmics#21]
Are spanning issues displayed on the enddate.
Or are they displayed between startdate to enddate.

https://github.com/thegcat/redmine_ical/issues/8

**Comment by fs5** [comment]
I cannot speak for forks of the plugin. 

This plugin is configurable globally via the plugin settings: https://my.redmine/settings/plugin/redmine_ics_export, or on a per user basis: https://my.redmine/my/redmics_settings, or on a per-URL basis by adding certain URL parameters to the Icalendar-URLs (see https://github.com/buschmais/redmics/blob/master/app/controllers/i_calendar_controller.rb#L72)
