### ISSUE TITLE
Does not work with Redmine 3.4.x

### ISSUE THREAD

**Issue by acki** [buschmais/redmics#22]
The issues overview generate a 404 with Redmics in place.
Can you take a look into this?

```
  Rendered issues/_sidebar.html.erb (40.0ms)
  Rendered issues/index.html.erb within layouts/base (258.4ms)
Missing template, responding with 404
```

Cheers
Christoph

**Comment by sachilles** [comment]
Hi there,

I can confirm the issue. After installing redmics I can neither open the configuration page of the plugin nor open any ticket without getting an 404 page.

Please help!

Best regards

**Comment by fs5** [comment]
Please provide more information. I see no issues with Redmine 3.4.4.stable.17235

**Comment by sachilles** [comment]
Hi,

thanks for your reply. Indeed the folder name in the plugin directory wasn't correctly named.

Best regards
