### ISSUE TITLE
Feature Request: Add ics to issue and use caldav

### ISSUE THREAD

**Issue by shemgp** [buschmais/redmics#25]
This plugin is nice. It would be great if it was able to do CalDav ics to issue to, then issues can be synced to any Caldav enabled clients (eg. Thunderbird, etc).

Thank you for considering this.

**Comment by fs5** [comment]
There are no plans to incorporate CalDAV features.

If you want to subscribe to the provided ICS links via CalDAV, please consider to use an external bind within your CalDAV-infrastructure, e.g. DaviCal: https://wiki.davical.org/w/External_Bind, or NextCloud -> Calendar -> new subscription
