### ISSUE TITLE
Should this work with Redmine 3.3.9 and latest Thunderbird 60.8.0

### ISSUE THREAD

**Issue by RolandSM** [buschmais/redmics#26]
Hello,
I installed the plugin and there was no error, when I use in my Redmine 3.3.9 the 3 file and put it in the named folder.
But when I insert a link into my current Thunderbird no issues are coming? Also no error?

**Comment by fs5** [comment]
I am not providing end-user support, sorry!

The calendar link of your choice (my issues/assigned issues/all isssues/...) can be subscribed to in Thunderbird as "Network Calendar" -> "iCalendar (ICS)".

Please double-check what is actually included in the ICS-file that is downloaded once you click on any of the calendar links. Please note: Issues must have at least a due date to become visible in the ICS export.
