### ISSUE TITLE
Third party plugin breaks the calendars.

### ISSUE THREAD

**Issue by flowgunso** [buschmais/redmics#28]
The plugin [RedmineUp Tags](https://www.redmine.org/plugins/redmineup_tags) breaks the calendars. Issues and versions are not displayed when the plugin is installed.

The logs does not show any particular issues, but adding `@controller.logger.info('Events:' + events)` at the end of https://github.com/buschmais/redmics/blob/a20b73e33646e753e498a97939f8ee4fc5ce57b9/lib/redmics/export.rb#L51-L53 with the plugin installed, not a single event is collected:
`redmine_1  | I, [2020-03-12T19:50:44.573770 #1]  INFO -- : Events:[]`
Events are properly collected when the plugin is not installed.

**Comment by fs5** [comment]
The other plugin is not available without registration.

**Comment by flowgunso** [comment]
How does that make it not a bug?

**Comment by fs5** [comment]
There is no use in arguing with me. Just read https://www.redmineup.com/pages/terms-and-conditions and judge for yourself. Even discussing their code here could possible infringe these terms. You are free to provide a patch, though.

**Comment by flowgunso** [comment]
> Even discussing their code here could possible infringe these terms.

I don't read that anywhere in their terms.

However I do read that:
- The Ruby code portions are GPL
- Any other file is proprietary. Redistribution is not allowed without written permission, e.g. on GitHub

Anyway, it's not their code that needs patching, so nothing to worry about.

About patching, I might look into it. But this has a very low priority for me and I have never written any Ruby yet.

If you don't mind, I may ask for a bug tracing review once or twice before I PR.
