### ISSUE TITLE
Due date as end date of the calendar event?

### ISSUE THREAD

**Issue by gigjozsa** [buschmais/redmics#36]
First, many thanks for the plugin. It is quite some way towards what we want. My suggestion would be to consider to make the due date in the Redmine issues the end date of the event in the ical calendar events.

**Comment by gigjozsa** [comment]
Correction: I now saw that the calendar only displays the due date. So I'd suggest to make the event ranging from the start to the due date.

**Comment by fs5** [comment]
Available as a user setting: <baseUrl>/my/redmics_settings
